// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruuirdfkpfscvgkmvvez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1dWlyZGZrcGZzY3Zna212dmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDU4NzcsImV4cCI6MjA3MTYyMTg3N30.eWS8oAqvQDVHHTdeM83um1mfYXdzJfYofqr2WWUmCjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});